exclude: "docs/"

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.2  # Use the latest version of ruff
    hooks:
      - id: ruff
        args: ["--fix", "--config=pyproject.toml"]
        language: python
        language_version: python3.12
        types: [python]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: python
        pass_filenames: false
        types: [python]

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=100]
        exclude: tests