name: Generate Documentation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  generate-doc:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry via pip
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Deploy to GitHub Pages
      run: |
        poetry run mkdocs gh-deploy --force --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
